name: Benchmark

on: push

jobs:
  ci:
    name: Lint and check format.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno bench --unstable
